### ISSUE TITLE
The data contract type 'SMSApi.Api.Response.Error' cannot be deserialized because the required data member 'message' was not found.

### ISSUE THREAD

**Issue by mateusznj** [smsapi/smsapi-csharp-client#34]
While testing the request as below - I get the following error (token and id hidden):

```
SMSApi.Api.IClient client = new SMSApi.Api.ClientOAuth("token");
var smsApi = new SMSApi.Api.SMSFactory(client);

string[] ids = { "id1", "id2" };
var resultSms = await smsApi.ActionGet()
        .Ids(ids)
        .ExecuteAsync();
```

```
System.Runtime.Serialization.SerializationException: 'The data contract type 'SMSApi.Api.Response.Error' cannot be deserialized because the required data member 'message' was not found.'
```

StackTrace:
```
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowMissingRequiredMembers(Object obj, XmlDictionaryString[] memberNames, Byte[] expectedElements, Byte[] requiredElements) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/XmlObjectSerializerReadContextComplexJson.cs:line 328
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/JsonClassDataContract.cs:line 94
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/JsonDataContract.cs:line 76
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/XmlObjectSerializerReadContextComplexJson.cs:line 37
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializerReadContext.cs:line 196
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializerReadContextComplex.cs:line 78
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializer.cs:line 427
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializer.cs:line 290
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializer.cs:line 312
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializer.cs:line 236
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializer.cs:line 218
   at SMSApi.Api.Action.Base`1.Deserialize[TT](Stream data)
   at SMSApi.Api.Action.Base`1.HandleError(Stream data)
```

**Comment by ptrkudla** [comment]
Hello,

I forwarded it to our IT Department.

Best regards,
Piotr Kudla

**Comment by jakublabno** [comment]
@mateusznj Please let us know, which version you are using.

**Comment by mateusznj** [comment]
@jakublabno version 2.0.1
